---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ kubernetes.apiserver.advertise_address }}" --pod-network-cidr=10.244.0.0/16 {{ kubernetes.apiserver.cert_extra_sans | join(' ') }}

- name: Create Directory ~/.kube for default user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory

- name: Setup kubeconfig for default user
  ansible.builtin.copy: 
    remote_src: yes
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,g=r,o=r
    backup: yes

- name: Create Directory ~/.kube
  file:
    path: "~/.kube"
    state: directory

- name: Setup kubeconfig
  ansible.builtin.copy: 
    remote_src: yes
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"
    backup: yes

- name: Create Directory ~/kubernetes
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/kubernetes/networks"
    - "~/kubernetes/dashboard"
    - "~/kubernetes/monitoring"

# Download and apply manifest
- name: Download flunnel network for kubernets cluster
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: ~/kubernetes/networks/kube-flannel.yml
    mode: '0664'

- name: Apply Network Policy to kubernetes cluster
  command: kubectl apply -f ~/kubernetes/networks/kube-flannel.yml