- name: Install kubernetes-dashboard using helm
  hosts: ["k8s_control_panel"]
  become: true
  roles:
    - monitoring/dashboard
    - monitoring/prometheus
  vars: 
    kubernetes:
      control_panel:
        node_isolation: true
      dashboard:
        enabled: true
        namespace: kubernetes-dashboard
      prometheus:
        enabled: true
        namespace: gitlab-managed-apps