---
- name: Install docker-ce
  hosts: all
  roles: 
    - docker/roles/common
    - docker/roles/docker

- name: Configure docker options
  hosts: all
  roles:
    - docker/roles/options

- name: Todo before install k8s cluster
  hosts: all
  roles:
    - common
