---
- name: Install docker-ce
  hosts: ["dockerd"]
  become: true
  roles: 
    - docker/roles/common
    - docker/roles/docker

- name: Configure docker options
  become: true
  hosts: ["dockerd"]
  roles:
    - docker/roles/options

- name: Todo before install k8s cluster
  hosts: ["dockerd", "kubernetes"]
  become: true
  roles:
    - common

- name: Install kubeadm, kubernetes-cli, and kubelet
  hosts: ["dockerd", "kubernetes"]
  become: true
  roles:
    - kubeadm
