---
## required to run site.yaml, site-init-cluster.yaml before this playbooks
- name: Resetting kubernetes cluster
  hosts: ["k8s_control_panel", "k8s_worker"]
  become: true
  roles:
    - k8s-cluster/reset