---
- name: Add firewalld for Kubernetes API server
  ansible.posix.firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    zone: public

- name: Add firewalld for etcd server client API
  ansible.posix.firewalld:
    port: 2379-2380/tcp
    permanent: yes
    state: enabled
    zone: public

- name: Add firewalld for Kubelet API
  ansible.posix.firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled
    zone: public

- name: Add firewalld for kube-scheduler
  ansible.posix.firewalld:
    port: 10259/tcp
    permanent: yes
    state: enabled
    zone: public

- name: Add firewalld for kube-controller-manager
  ansible.posix.firewalld:
    port: 10257/tcp
    permanent: yes
    state: enabled
    zone: public

- name: Add firewalld for NodePort Services
  ansible.posix.firewalld:
    port: 30000-32767/tcp
    permanent: yes
    state: enabled
    zone: public