---
- name: Add rules for Kubernetes on CentOS
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  loop: 
    - 6443/tcp # Kubernetes API server
    - 2379-2380/tcp # etcd server client API
    - 10250/tcp # Kubelet API
    - 10259/tcp # kube-scheduler
    - 10257/tcp # kube-controller-manager
    - 30000-32767/tcp # NodePort Services
  notify: 
    - Reload firewalld
