---
- name: Add latest prometheus repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
  when: kubernetes.prometheus.enabled | bool

- name: Deploy latest version of prometheus chart
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: "{{ kubernetes.prometheus.namespace }}"
    create_namespace: true
  when: kubernetes.prometheus.enabled | bool