---
- name: Add latest prometheus repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
  when: kubernetes.prometheus.enabled | bool

## Update file ../templates/values.yaml from https://gitlab.com/gitlab-org/project-templates/cluster-management/-/raw/master/applications/prometheus/values.yaml
- name: Deploy latest version of prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: "{{ kubernetes.prometheus.namespace }}"
    create_namespace: true
    release_values : "{{ lookup('template', 'values.yaml') | from_yaml }}"
  when: kubernetes.prometheus.enabled | bool

- name: Patch resource on pvc/prometheus-prometheus-server
  k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: prometheus-prometheus-server
        namespace: "{{ kubernetes.prometheus.namespace }}"
      spec:
        volumeMode: Filesystem
        volumeName: prometheus-prometheus-server-pv
  when: kubernetes.prometheus.enabled | bool

- name: Create Directory /var/lib/prometheus/data for storing data
  file:
    path: "/var/lib/prometheus/data"
    state: directory
    mode: u=rwx,g=rwx,o=rwx

- name: Create persistence volume for storing data link by pvc/prometheus-prometheus-server
  k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        labels:
          app: prometheus
          component: server
          heritage: Helm
          release: prometheus
        name: prometheus-prometheus-server-pv
        namespace: "{{ kubernetes.prometheus.namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        capacity:
          storage: 10Gi
        claimRef:
          apiVersion: v1
          kind: PersistentVolumeClaim
          name: prometheus-prometheus-server
          namespace: "{{ kubernetes.prometheus.namespace }}"
        hostPath:
          path: "/var/lib/prometheus/data"
  when: kubernetes.prometheus.enabled | bool
