---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ ansible_ssh_host }}"  --apiserver-cert-extra-sans="{{ ansible_ssh_host }}"  --pod-network-cidr=192.168.0.0/16

- name: Create Directory ~/.kube
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory

- name: Setup kubeconfig
  ansible.builtin.copy: 
    remote_src: yes
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,g=r,o=r
    backup: yes